-- Allow NULL values for size columns to distinguish "N/A" (Not Manufactured) from 0 (Out of Stock)
ALTER TABLE inventory 
MODIFY xs INT NULL DEFAULT NULL,
MODIFY s INT NULL DEFAULT NULL,
MODIFY m INT NULL DEFAULT NULL,
MODIFY l INT NULL DEFAULT NULL,
MODIFY xl INT NULL DEFAULT NULL,
MODIFY xxl INT NULL DEFAULT NULL,
MODIFY xxxl INT NULL DEFAULT NULL;
